# Generated by Django 5.0.6 on 2024-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataforimagecase',
            name='plate_num',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
